languages: ['en', 'fa']
language_default: 'en'
current_language: 'en'
exclude_from_localizations: ["javascript", "images", "css"]
title: Sareh Heidari
email: hello@sareh.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Sareh Heidari is a web developer. Have a look at her projects, skills and interests. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sareh.co.uk" # the base hostname & protocol for your site
twitter_username: sareh88
github_username:  sareh
future: true
# Build settings
markdown: kramdown
exclude: ['README.md', '.gitignore', 'LICENSE']
logo: "/images/sareh-3-blue900-web-optimised-100px.svg"
fa: 
  menu_items:
    about: درباره من
    projects: پروژه ها
    blog: وبلاگ
    interests: موضوعات مورد علاقه
    contact: تماس
    english: English
  home: صفحه اصلی
  about: درباره من
  projects: پروژه ها
  blog: وبلاگ
  interests: موضوعات مورد علاقه
  contact: تماس
  site_title: "ساره حیدری"
  site_subtitle: "برنامه نویس وبسایت"
  social_media: "شبکه‌های اجتماعی"
en: 
  menu_items:
    about: About Me
    projects: Projects
    blog: Blog
    interests: Interests
    contact: Contact
    farsi: فارسی
  home: Home
  about: "About Me"
  projects: Projects
  blog: Blog
  interests: Interests
  contact: Contact
  site_title: "Sareh Heidari"
  site_subtitle: "Web Developer"
  social_media: "Social Media"