# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
gems: ['jekyll-multiple-languages-plugin']
languages: ['en', 'fa']
language_default: 'en'
exclude_from_localizations: ["javascript", "images", "css"]
title: Sareh Heidari
email: hello@sareh.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Sareh Heidari is a web developer. Have a look at her projects, skills and interests. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sareh.co.uk" # the base hostname & protocol for your site
twitter_username: sareh88
github_username:  sareh
future: true
# Build settings
markdown: kramdown
