languages: ['en', 'fa']
language_default: 'en'
current_language: 'en'
exclude_from_localizations: ["javascript", "images", "css"]
title: Sareh Heidari
email: hello@sareh.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Sareh Heidari is a web developer. Have a look at her projects, skills and interests. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sareh.co.uk" # the base hostname & protocol for your site
twitter_username: sareh88
github_username:  sareh
future: true
# Build settings
markdown: kramdown
exclude: ['README.md', '.gitignore', 'LICENSE']